use_frameworks!

platform :ios, '10.0'

target 'CoreMLImage_Example' do
  pod 'CoreMLImage', :path => '../'

  target 'CoreMLImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
