use_frameworks!

platform :ios, '10.0'

target 'Inpainting_Example' do
  pod 'Inpainting', :path => '../'

  target 'Inpainting_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
